### ISSUE TITLE
report-concurrency fails with fatal error

### ISSUE THREAD

**Issue by BBenedikt** [tmuras/moosh#330]
- moosh version:  [1c4c7b2](https://github.com/tmuras/moosh/commit/1c4c7b29cdd51b95ef161cf38c1a9b2593d5b6d2) (current HEAD of master)
- moodle version: 3.8.3+ (20200527)
    - database: MySQL 5.7.30
- php version: 7.2.24
- operating system: Ubuntu 18.04

### Actual behaviour

```
# moosh report-concurrency -f 20200721 -t 20200722 -p 30

PHP Notice:  Undefined property: stdClass::$langotherroot in /home/user/moosh/includes/moodle/lib/moodlelib.php on line 7140

Notice: Undefined property: stdClass::$langotherroot in /home/user/moosh/includes/moodle/lib/moodlelib.php on line 7140
PHP Notice:  Undefined property: stdClass::$langlocalroot in /home/user/moosh/includes/moodle/lib/moodlelib.php on line 7140

Notice: Undefined property: stdClass::$langlocalroot in /home/user/moosh/includes/moodle/lib/moodlelib.php on line 7140
PHP Fatal error:  Uncaught dml_read_exception: error/dmlreadexception in /home/user/moosh/includes/moodle/lib/dml/moodle_database.php:486
Stack trace:
#0 /home/user/moosh/includes/moodle/lib/dml/mysqli_native_moodle_database.php(1245): moodle_database->query_end(false)
#1 /home/user/moosh/Moosh/Command/Generic/Report/ReportConcurrency.php(228): mysqli_native_moodle_database->get_records_sql('SELECT\n        ...')
#2 /home/user/moosh/moosh.php(354): Moosh\Command\Generic\Report\ReportConcurrency->execute()
#3 {main}
  thrown in /home/user/moosh/includes/moodle/lib/dml/moodle_database.php on line 486

Fatal error: Uncaught dml_read_exception: error/dmlreadexception in /home/user/moosh/includes/moodle/lib/dml/moodle_database.php:486
Stack trace:
#0 /home/user/moosh/includes/moodle/lib/dml/mysqli_native_moodle_database.php(1245): moodle_database->query_end(false)
#1 /home/user/moosh/Moosh/Command/Generic/Report/ReportConcurrency.php(228): mysqli_native_moodle_database->get_records_sql('SELECT\n        ...')
#2 /home/user/moosh/moosh.php(354): Moosh\Command\Generic\Report\ReportConcurrency->execute()
#3 {main}
  thrown in /home/user/moosh/includes/moodle/lib/dml/moodle_database.php on line 486 

```

### Expected behaviour

Get information about concurrent users online during specified time period 

### Steps to reproduce
Install via git, symlink moosh system-wide, then run:
```
 moosh report-concurrency -f 20200721 -t 20200722 -p 30
```

**Comment by tmuras** [comment]
Works OK in moosh2:
moosh report:concurrency --from=2025-01-01 --to=2025-12-31 --period=1
https://moosh-online.com/moosh2/#/commands/report/concurrency
