### ISSUE TITLE
Moosh 0.32 does not work with Moodle 3.10

### ISSUE THREAD

**Issue by kiklop74** [tmuras/moosh#347]
- moosh version: 0.32
- moodle version: 3.10+
    - database: mariadb 10.3
- php version: 7.2
- operating system: Linux

### Actual behaviour

```sh
PHP Fatal error:  Uncaught Exception: Unable to determine branch version from '/path/to/moodle/version.php' in /home/darko/projects/moosh/includes/functions.php:147
Stack trace:
#0 /home/darko/projects/moosh/moosh.php(74): moosh_moodle_version('/home/darko/pro...')
#1 {main}
  thrown in /home/darko/projects/moosh/includes/functions.php on line 147

Fatal error: Uncaught Exception: Unable to determine branch version from '/path/to/moodle/version.php' in /home/darko/projects/moosh/includes/functions.php:147
Stack trace:
#0 /home/darko/projects/moosh/moosh.php(74): moosh_moodle_version('/home/darko/pro...')
#1 {main}
  thrown in /home/darko/projects/moosh/includes/functions.php on line 147
```

### Expected behaviour

List allavailable  commands

### Steps to reproduce

Setup stock Moodle 3.10 site.
Position yourself in the root directory of Moodle in terminal
execute moosh

Most likely regular expression is incorrect in function \moosh_moodle_version

**Comment by proedie** [comment]
This should be fixed with #344

**Comment by tmuras** [comment]
It should be OK now.
