### ISSUE TITLE
Option conflict: -h is already defined

### ISSUE THREAD

**Issue by jumabgz** [tmuras/moosh#437]
Hi, I just upgraded to moosh 1.9 and it does not work. It throws _PHP Fatal error_ like I show below:

- moosh version: 1.9 (2023051200)
- moodle version: 4.1.3+ (2022112803.03)
    - database: PostgreSQL 12.11
- php version: 8.0.21
- operating system: CentOS 7 (also tested on RHEL 8.7).

### Actual behaviour
```
-bash-4.2$ /usr/bin/php /opt/moosh/moosh.php  | head
PHP Fatal error:  Uncaught GetOptionKit\Exception\OptionConflictException: Option conflict: -h is already defined. in /opt/moosh-19/vendor/corneltek/getoptionkit/src/OptionCollection.php:124
Stack trace:
#0 /opt/moosh-19/vendor/corneltek/getoptionkit/src/OptionCollection.php(98): GetOptionKit\OptionCollection->addOption(Object(GetOptionKit\Option))
#1 /opt/moosh-19/Moosh/MooshCommand.php(202): GetOptionKit\OptionCollection->add('h|hash:', 'Sets the hash m...')
#2 /opt/moosh-19/Moosh/Command/Moodle310/Cache/CacheAddMemStore.php(51): Moosh\MooshCommand->addOption('h|hash:', 'Sets the hash m...')
#3 /opt/moosh-19/moosh.php(88): Moosh\Command\Moodle310\Cache\CacheAddMemStore->__construct()
#4 {main}
  thrown in /opt/moosh-19/vendor/corneltek/getoptionkit/src/OptionCollection.php on line 124
```

### Expected behaviour
It should show moosh version and list of commands.

### Steps to reproduce

1. Install moosh 1.9.
1. Execute: _/usr/bin/php /opt/moosh/moosh.php_

Regards

**Comment by tmuras** [comment]
Fixed in commit 66b698332bfd6df523a838fa29bc7019e34afc08

**Comment by jumabgz** [comment]
Hi @tmuras ,

I dont know if I'm doing something wrong, but I just try again with Moosh 1.10 and it keeps throwing same error:

```
-bash-4.2$ /usr/bin/php /opt/moosh/moosh.php | head
PHP Fatal error:  Uncaught GetOptionKit\Exception\OptionConflictException: Option conflict: -h is already defined. in /opt/moosh-110/vendor/corneltek/getoptionkit/src/OptionCollection.php:124
Stack trace:
#0 /opt/moosh-110/vendor/corneltek/getoptionkit/src/OptionCollection.php(98): GetOptionKit\OptionCollection->addOption(Object(GetOptionKit\Option))
#1 /opt/moosh-110/Moosh/MooshCommand.php(202): GetOptionKit\OptionCollection->add('h|hash:', 'Sets the hash m...')
#2 /opt/moosh-110/Moosh/Command/Moodle310/Cache/CacheAddMemStore.php(51): Moosh\MooshCommand->addOption('h|hash:', 'Sets the hash m...')
#3 /opt/moosh-110/moosh.php(88): Moosh\Command\Moodle310\Cache\CacheAddMemStore->__construct()
#4 {main}
  thrown in /opt/moosh-110/vendor/corneltek/getoptionkit/src/OptionCollection.php on line 124
```

Regards

**Comment by tmuras** [comment]
It was only a partial fix - try 1.11.

**Comment by jumabgz** [comment]
Thank you, now its working fine.

**Comment by CartierPierre** [comment]
Hello
I have the same with these versions :
moosh : 1.17 (build moosh_moodle43_2024021300)
moodle : 4.3+ (Build: 20231110)
php : 8.2.7

Error :
```bash
PHP Fatal error:  Uncaught GetOptionKit\Exception\OptionConflictException: Option conflict: -h is already defined. in /opt/moosh/vendor/corneltek/getoptionkit/src/OptionCollection.php:124
Stack trace:
#0 /opt/moosh/vendor/corneltek/getoptionkit/src/OptionCollection.php(98): GetOptionKit\OptionCollection->addOption()
#1 /opt/moosh/Moosh/MooshCommand.php(202): GetOptionKit\OptionCollection->add()
#2 /opt/moosh/Moosh/Command/Moodle23/GradeCategory/GradeCategoryList.php(18): Moosh\MooshCommand->addOption()
#3 /opt/moosh/moosh.php(88): Moosh\Command\Moodle23\GradeCategory\GradeCategoryList->__construct()
#4 {main}
  thrown in /opt/moosh/vendor/corneltek/getoptionkit/src/OptionCollection.php on line 124

```

**Comment by CartierPierre** [comment]
Oh, I saw you fixed that, I had trouble with updating the repo (still have old files)
